# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  solutionPath: './ClothingStore'
  appProjectPath: 'ClothingStore.WebApp'

steps:
- script: dotnet build "$(solutionPath)" --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '$(appProjectPath)'
    publishWebProjects: false
    arguments: >-
      --configuration $(buildConfiguration)
      --output $(System.DefaultWorkingDirectory)/publish
    zipAfterPublish: true
  displayName: dotnet publish
- task: AzureRmWebAppDeployment@3
  inputs:
    # based on name given to azure resource manager service connection
    azureSubscription: 'andy-azure'
    # the name of app service resource in azure (also subdomain of URL)
    WebAppName: 'ajlclothingstore'
    Package: $(System.DefaultWorkingDirectory)/publish/*.zip